### ISSUE TITLE
Square function component needed

### ISSUE THREAD

**Issue by Toluwanee** [emmanuelonwukwe/tic-tac-toe#10]
A square component function is needed for the board. The component prototype should take the form `Square({ value, onSquareClick })` and return jsx button. The button value should be `value ` and the button should have `onSquareClick={onSquareClick }` property.

**Comment by BivanBhee** [comment]
Can you please, explain more.

**Comment by Toluwanee** [comment]
Using react in our current project, create a jsx function component of name
Square({ value, onSquareClick }) and return jsx button. The button value should be value  and the button should have onSquareClick={onSquareClick } property.

**Comment by BivanBhee** [comment]
Noted!
Will work on it right away.
